"""
Django settings for lendr project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import socket
import ssl
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_local_env():
    env_path = BASE_DIR / '.env'
    if not env_path.exists():
        return

    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip())


load_local_env()


def env_value(*names, default=""):
    for name in names:
        value = os.environ.get(name)
        if value:
            return value
    return default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^-^22dde$h8a^2s5ldssz2!6ij@6zrgem=#bc=1fqr!9c0(!)q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")


def detect_lan_ip():
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as probe:
            probe.connect(("8.8.8.8", 80))
            return probe.getsockname()[0]
    except OSError:
        return ""


LOCAL_LAN_IP = detect_lan_ip()
if DEBUG and LOCAL_LAN_IP and LOCAL_LAN_IP not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(LOCAL_LAN_IP)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'equipment',
    'lending',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.RequestLogMiddleware',
]

ROOT_URLCONF = 'lendr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.portal_role',
            ],
        },
    },
]

WSGI_APPLICATION = 'lendr.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

db_options = {
    'charset': 'utf8mb4',
}
if os.environ.get("DB_SSL", "true").lower() == "true":
    ssl_context = ssl.create_default_context()
    ssl_context.check_hostname = False
    ssl_context.verify_mode = ssl.CERT_NONE
    db_options['ssl'] = ssl_context

DATABASES = {
    'default': {
        # Django connects to MariaDB through its MySQL-compatible database backend.
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get("DB_NAME", "lendr"),
        'USER': os.environ.get("DB_USER", ""),
        'PASSWORD': os.environ.get("DB_PASSWORD", ""),
        'HOST': os.environ.get("DB_HOST", ""),
        'PORT': os.environ.get("DB_PORT", "3306"),
        'OPTIONS': db_options,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kuala_Lumpur'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'accounts:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'
PASSWORD_RESET_TIMEOUT = 300

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_CURRENCY = os.environ.get("STRIPE_CURRENCY", "myr").lower()

EMAIL_PROVIDER = os.environ.get("EMAIL_PROVIDER", "").lower()
BREVO_ENABLED = EMAIL_PROVIDER == "brevo" or bool(os.environ.get("BREVO_SMTP_KEY"))

EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend" if BREVO_ENABLED or os.environ.get("EMAIL_HOST") else "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = env_value("EMAIL_HOST", default="smtp-relay.brevo.com" if BREVO_ENABLED else "")
EMAIL_PORT = int(env_value("EMAIL_PORT", "BREVO_SMTP_PORT", default="587"))
EMAIL_HOST_USER = env_value("EMAIL_HOST_USER", "BREVO_SMTP_USERNAME")
EMAIL_HOST_PASSWORD = env_value("EMAIL_HOST_PASSWORD", "BREVO_SMTP_KEY")
EMAIL_USE_TLS = env_value("EMAIL_USE_TLS", "BREVO_EMAIL_USE_TLS", default="true").lower() == "true"
DEFAULT_FROM_EMAIL = env_value("DEFAULT_FROM_EMAIL", "BREVO_FROM_EMAIL", default="lendr+ <no-reply@lendr.local>")
