# Generated by Django 6.0.4 on 2026-05-09 15:52

import django.core.validators
import django.db.models.deletion
import lending.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_mariadb_temporal_and_scheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('borrowed', 'Borrowed'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='ReturnPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('top', 'Top'), ('bottom', 'Bottom')], max_length=20)),
                ('image', models.FileField(upload_to=lending.models.return_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lending_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_photos', to='lending.lendingrequest')),
            ],
            options={
                'ordering': ['side'],
                'unique_together': {('lending_request', 'side')},
            },
        ),
    ]
