# Generated by Django 6.0.4 on 2026-05-09 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0003_alter_lendingrequest_status_returnphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReturnPhoto',
        ),
    ]
