# Generated by Django 6.0.4 on 2026-05-10 13:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0004_delete_returnphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='product_penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
